services:
  db:
    image: mysql:9.0.1
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p${DB_PASS}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASS
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$DB_NAME
    networks:
      - app

  cache:
    image: redis:7.4.0
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app
